"""Persistence interfaces for Phase 1A domain records."""

from __future__ import annotations

from typing import Protocol

from regops_api.domain_models import (
    ActionRecord,
    AuditEvent,
    CaseTag,
    InternalReviewTask,
    RegulationRecord,
    RunCheckpoint,
    ShadowContractSnapshot,
    SyntheticContract,
)
from regops_api.schemas import Approval, AuditReport, Finding, Obligation, Run


class RecordNotFoundError(LookupError):
    """Raised when a requested repository record does not exist."""


class DuplicateRecordError(RuntimeError):
    """Raised when a unique record or idempotency key already exists."""


class RunRepository(Protocol):
    def add_run(self, run: Run) -> None: ...

    def get_run(self, run_id: str) -> Run: ...

    def update_run(self, run: Run) -> None: ...


class RegulationRepository(Protocol):
    def add_regulation(self, record: RegulationRecord) -> None: ...

    def get_regulation(self, regulation_id: str) -> RegulationRecord: ...

    def find_regulation_by_hash(self, content_sha256: str) -> RegulationRecord | None: ...

    def list_regulations_by_source(self, source_filename: str) -> list[RegulationRecord]: ...


class ObligationRepository(Protocol):
    def add_obligations(self, run_id: str, obligations: list[Obligation]) -> None: ...

    def list_obligations(self, run_id: str) -> list[Obligation]: ...


class SyntheticContractRepository(Protocol):
    def add_synthetic_contract(self, contract: SyntheticContract) -> None: ...

    def get_synthetic_contract(self, contract_id: str) -> SyntheticContract: ...

    def list_synthetic_contracts(self) -> list[SyntheticContract]: ...

    def save_shadow_snapshot(self, snapshot: ShadowContractSnapshot) -> None: ...

    def get_shadow_snapshot(self, snapshot_id: str) -> ShadowContractSnapshot: ...


class FindingRepository(Protocol):
    def add_findings(self, findings: list[Finding]) -> None: ...

    def get_finding(self, finding_id: str) -> Finding: ...

    def list_findings(self, run_id: str) -> list[Finding]: ...

    def update_finding(self, finding: Finding) -> None: ...


class ReviewTaskRepository(Protocol):
    def add_review_task(self, task: InternalReviewTask) -> None: ...

    def get_review_task(self, task_id: str) -> InternalReviewTask: ...

    def list_review_tasks(self, run_id: str) -> list[InternalReviewTask]: ...


class ApprovalRepository(Protocol):
    def add_approval(self, approval: Approval) -> None: ...

    def get_approval(self, approval_id: str) -> Approval: ...

    def update_approval(self, approval: Approval) -> None: ...

    def list_approvals(self, run_id: str) -> list[Approval]: ...


class AuditRepository(Protocol):
    def append_audit_event(self, event: AuditEvent) -> None: ...

    def list_audit_events(self, run_id: str) -> list[AuditEvent]: ...

    def save_audit_report(self, report: AuditReport) -> None: ...

    def get_audit_report(self, run_id: str) -> AuditReport: ...


class ActionRepository(Protocol):
    def add_action(self, record: ActionRecord) -> None: ...

    def get_action(self, action_id: str) -> ActionRecord: ...

    def find_action_by_idempotency_key(self, idempotency_key: str) -> ActionRecord | None: ...

    def update_action(self, record: ActionRecord) -> None: ...

    def list_actions(self, run_id: str) -> list[ActionRecord]: ...


class CheckpointRepository(Protocol):
    def append_checkpoint(self, checkpoint: RunCheckpoint) -> None: ...

    def latest_checkpoint(self, run_id: str) -> RunCheckpoint | None: ...

    def list_checkpoints(self, run_id: str) -> list[RunCheckpoint]: ...


class CaseTagRepository(Protocol):
    def add_case_tag(self, tag: CaseTag) -> None: ...

    def list_case_tags(self, run_id: str) -> list[CaseTag]: ...
